Repository harshit-paneri/canvas-game, pull requests merged in 2022-10, with the labels that each got.

#17 images
  Images/Screenshot (192).png
  Images/Screenshot (193).png
  Images/Screenshot (194).png
  Images/Screenshot (195).png
  Images/Screenshot (196).png
  README.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#22 Buttons Changed in Dynamic Looks
  martial/main.html
Labels: good first issue, hackerfest-assigned

#23 Manage Readme Boolean
  README.md
Labels: hacktoberfest-accepted

#26 added background and button color
  CONTRIBUTING.md
  martial/background.jpg
  martial/main.html
Labels: hacktoberfest-accepted

#28 Text align center.
  martial/main.html
Labels: hacktoberfest-accepted

#29 changed the topic text color and button color
  martial/main.html
Labels: hacktoberfest-accepted

#30 Color change of button.
  martial/main.html
Labels: hacktoberfest-accepted

#33 Update README.md
  README.md
Labels: documentation, hacktoberfest-accepted

#34 background
  images/Blogenium-nature-wallpaper20.jpg
Labels: hacktoberfest-accepted

#35 Update Contributers.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#36 Block Image
  README.md
  images/Block.png
Labels: hacktoberfest-accepted

#37 Backward Image
  README.md
  images/Backward.png
Labels: hacktoberfest-accepted

#38 new_image
  images/7.png
Labels: hacktoberfest-accepted

#39 Refashioned the font family and renamed Text
  martial/main.html
Labels: hacktoberfest-accepted

#40 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#41 Background image changed of Martial-Page
  martial/Martial.png
  martial/main.html
Labels: hacktoberfest-accepted

#42 Update
  CONTRIBUTING.md
Labels: hacktoberfest-accepted
